#!/usr/bin/env node
var express = require('express');
var formidable = require('formidable');
var util = require('util');
var fs = require('fs');
var morgan = require('morgan');

var uploadDir = __dirname + '../static/uploads';
var staticDir = __dirname + '../static';
var documentRoot = __dirname + 'jekyll/_site/0';

var app = express();
app.use(morgan());
app.post('/upload', function (req, res) {
    var form = new formidable.IncomingForm();
    form.uploadDir = uploadDir;
    form.keepExtensions = true;
    form.parse(req, function(err, fields, files) {
        res.writeHead(200, {'content-type': 'text/plain'});
        res.write('received upload:\n\n');
        res.end(util.inspect({fields: fields, files: files}));
        fs.rename(files.upload.path,
	    uploadDir + '/' + files.upload.name, function(err) {});
    });
});
app.use(express.static(documentRoot));
app.use(express.directory(documentRoot));
app.use('/static', express.static(staticDir));
app.use(express.methodOverride());
app.use(app.router);
app.listen(8081);
